import { db } from '../../src/lib/db'
console.log('=== local in events NOT applied (failed/dead/pending) ===')
const bad = await db.hybridEvent.findMany({ where: { direction: 'in', status: { not: 'applied' } }, orderBy: { id: 'desc' }, take: 10 })
if (!bad.length) console.log('  none ✓')
for (const e of bad) console.log(`  #${e.id} ${e.status} ${e.entity}/${e.entityId} ${e.operation} attempts=${e.attempts} err=${e.lastError?.slice(0, 80)}`)
console.log('=== local in events after 12006 (post-cleanup arrivals) ===')
const recent = await db.hybridEvent.findMany({ where: { id: { gt: 12006 } }, orderBy: { id: 'asc' } })
if (!recent.length) console.log('  none — no events arrived after the cleanup')
for (const e of recent) console.log(`  #${e.id} ${e.direction}/${e.status} ${e.entity}/${e.entityId} ${e.operation} at=${e.createdAt.toISOString().slice(0,19)} err=${e.lastError?.slice(0, 90) ?? '-'}`)
console.log('=== newest hybrid_conflicts ===')
const cf = await db.hybridConflict.findMany({ orderBy: { id: 'desc' }, take: 5 })
for (const c of cf) console.log(`  #${c.id} ${c.entity}/${c.entityId} policy=${c.policy} resolution=${c.resolution} at=${c.resolvedAt.toISOString().slice(0,19)}`)
console.log('=== sync state keys ===')
for (const s of await db.hybridSyncState.findMany({ where: { key: { in: ['pull.cursor', 'pull.remaining', 'cloud.reachable', 'sync.paused', 'lastPushAt', 'lastPullAt'] } } }))
  console.log(`  ${s.key} = ${s.value}`)
await db.$disconnect()
