'use client'

// 9-b: AI manager briefing hero card for the admin dashboard (admin only —
// the parent mounts it after checking the session role; the API 403s
// otherwise). Self-contained: GET /api/ai/briefing (15-min server cache)
// with a 5-min client staleTime. The refresh button bumps the query key so
// the request carries ?refresh=1 and the server recomputes.
// P15: the briefing is generated by the consensus engine — the badge
// shows how many of the voting AI models agreed with the answer.

import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Clock, GitMerge, RotateCw, Sparkles, WifiOff } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { AnimatedNumber, FadeIn } from '@/components/ui/motion'
import { Skeleton } from '@/components/ui/skeleton'
import { fetcher } from '@/lib/api'
import { formatCurrency, formatTime } from '@/lib/format'
import { useI18n } from '@/lib/i18n'
import { cn } from '@/lib/utils'

export type AiBriefingResponse = {
  briefing: {
    text: string
    provider: string
    model: string
    consensus: {
      agreed: number
      total: number
      strategy: string
      providers: string[]
    }
    generatedAt: string
    snapshot: {
      revenueToday: number
      ordersToday: number
      avgCheck: number
      tipsToday: number
      occupiedNow: number
    }
  }
  cached: boolean
}

/** Provider pill label for the five consensus providers (z.ai removed p15). */
export function aiProviderLabel(provider: string, t: (k: string) => string): string {
  if (provider === 'groq') return t('ai.providerGroq')
  if (provider === 'openrouter') return t('ai.providerOpenrouter')
  if (provider === 'nvidia') return t('ai.providerNvidia')
  if (provider === 'gemini') return t('ai.providerGemini')
  if (provider === 'huggingface') return t('ai.providerHuggingface')
  return t('ai.providerUnknown')
}

export default function AiBriefingCard() {
  const { t } = useI18n()
  // Refresh bumps the query key; tick > 0 asks the server to bypass its cache.
  const [refreshTick, setRefreshTick] = useState(0)

  const { data, isPending, isError, isFetching } = useQuery({
    queryKey: ['ai-briefing', refreshTick],
    queryFn: () =>
      fetcher<AiBriefingResponse>(`/api/ai/briefing${refreshTick > 0 ? '?refresh=1' : ''}`),
    staleTime: 5 * 60_000,
    retry: false,
  })

  const handleRefresh = () => setRefreshTick((tick) => tick + 1)

  if (isPending) {
    return (
      <Card className="card-elevated-2 gap-0 overflow-hidden p-0" aria-busy="true">
        <div className="bg-gradient-to-r from-primary/10 via-accent/50 to-warning/15 p-4 sm:p-6">
          <div className="flex items-center gap-3">
            <Skeleton className="size-10 rounded-xl" />
            <div className="flex-1 space-y-2">
              <Skeleton className="h-5 w-56" />
              <Skeleton className="h-3.5 w-72 max-w-full" />
            </div>
            <Skeleton className="h-6 w-20 rounded-full" />
          </div>
        </div>
        <div className="space-y-4 p-4 sm:p-6">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {Array.from({ length: 4 }, (_, i) => (
              <Skeleton key={i} className="h-16 rounded-lg" />
            ))}
          </div>
          <div className="space-y-2.5">
            {Array.from({ length: 5 }, (_, i) => (
              <Skeleton key={i} className="h-4 w-full" />
            ))}
          </div>
        </div>
      </Card>
    )
  }

  if (isError) {
    return (
      <Card className="card-elevated border-dashed p-4 sm:p-6">
        <div className="flex flex-col items-center gap-3 py-6 text-center">
          <div className="grid size-12 place-items-center rounded-full bg-muted">
            <WifiOff className="size-6 text-muted-foreground/70" aria-hidden />
          </div>
          <p className="max-w-md text-sm text-muted-foreground">{t('ai.briefingOffline')}</p>
          <Button variant="outline" className="h-11 gap-2 rounded-xl" onClick={handleRefresh}>
            <RotateCw className="size-4" aria-hidden />
            {t('ai.briefingRetry')}
          </Button>
        </div>
      </Card>
    )
  }

  const briefing = data.briefing
  const lines = briefing.text.split('\n').filter((line) => line.trim().length > 0)

  return (
    <FadeIn>
      <Card className="card-elevated-2 gap-0 overflow-hidden p-0">
        {/* Gradient hero header — plum → saffron wash (r48 tokens) */}
        <div className="bg-gradient-to-r from-primary/10 via-accent/50 to-warning/15 p-4 sm:p-6">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div className="flex min-w-0 items-center gap-3">
              <div className="grid size-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-primary/15 to-primary/5 text-primary shadow-sm ring-1 ring-black/5 dark:ring-white/10">
                <Sparkles className="size-5" aria-hidden />
              </div>
              <div className="min-w-0">
                <h2 className="truncate text-base font-bold tracking-tight">{t('ai.briefingTitle')}</h2>
                <p className="mt-0.5 text-xs text-muted-foreground">{t('ai.briefingSubtitle')}</p>
              </div>
            </div>
            <div className="flex shrink-0 items-center gap-2">
              {data.cached && (
                <Badge
                  variant="outline"
                  className="border-border/60 bg-background/70 text-[10px] font-medium text-muted-foreground"
                >
                  {t('ai.briefingCached')}
                </Badge>
              )}
              {briefing.consensus && briefing.consensus.total > 1 && (
                <Badge
                  variant="outline"
                  className="gap-1 border-emerald-300 bg-emerald-50/90 text-[10px] font-semibold text-emerald-700"
                  title={t('ai.consensusTitle')
                    .replace('{agreed}', String(briefing.consensus.agreed))
                    .replace('{total}', String(briefing.consensus.total))}
                >
                  <GitMerge className="size-3" aria-hidden />
                  {t('ai.consensusBadge')
                    .replace('{agreed}', String(briefing.consensus.agreed))
                    .replace('{total}', String(briefing.consensus.total))}
                </Badge>
              )}
              <Badge variant="secondary" className="bg-background/80 font-medium text-foreground/80 shadow-sm">
                {aiProviderLabel(briefing.provider, t)}
              </Badge>
              <Button
                variant="outline"
                className="h-11 w-11 rounded-xl bg-background/80 px-0 hover:bg-background/90"
                onClick={handleRefresh}
                disabled={isFetching}
                aria-label={t('ai.briefingRefresh')}
                title={t('ai.briefingRefresh')}
              >
                <RotateCw className={cn('size-4', isFetching && 'animate-spin')} aria-hidden />
              </Button>
            </div>
          </div>
          <p className="mt-3 flex items-center gap-1.5 text-[11px] text-muted-foreground">
            <Clock className="size-3" aria-hidden />
            <span className="tabular-nums">{formatTime(briefing.generatedAt)}</span>
          </p>
        </div>

        {/* Body */}
        <div className="space-y-4 p-4 sm:p-6">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <MiniStat
              label={t('ai.statRevenue')}
              value={briefing.snapshot.revenueToday}
              format={formatCurrency}
            />
            <MiniStat
              label={t('ai.statOrders')}
              value={briefing.snapshot.ordersToday}
              format={(v) => String(Math.round(v))}
            />
            <MiniStat
              label={t('ai.statAvgCheck')}
              value={briefing.snapshot.avgCheck}
              format={formatCurrency}
            />
            <MiniStat
              label={t('ai.statTips')}
              value={briefing.snapshot.tipsToday}
              format={formatCurrency}
            />
          </div>

          <div
            className="rms-scroll max-h-48 overflow-y-auto rounded-xl border border-border/60 bg-muted/50 p-4"
            aria-label={t('ai.briefingTitle')}
          >
            {lines.map((line, i) => {
              const bullet = line.trimStart().startsWith('- ')
              const text = bullet ? line.trimStart().slice(2) : line
              const isRecommendation = /^recommendation\b/i.test(text.trim())
              if (bullet) {
                return (
                  <p key={i} className="flex gap-2.5 py-0.5 text-sm leading-relaxed text-foreground/80">
                    <span className="mt-[7px] size-1.5 shrink-0 rounded-full bg-warning" aria-hidden />
                    <span>{text}</span>
                  </p>
                )
              }
              return (
                <p
                  key={i}
                  className={cn(
                    'py-0.5 text-sm leading-relaxed',
                    isRecommendation ? 'pt-2 font-semibold text-primary' : 'text-foreground/80',
                  )}
                >
                  {text}
                </p>
              )
            })}
          </div>
        </div>
      </Card>
    </FadeIn>
  )
}

function MiniStat({
  label,
  value,
  format,
}: {
  label: string
  /** Number values render through <AnimatedNumber> (spring counter). */
  value: string | number
  format?: (v: number) => string
}) {
  return (
    <div className="rounded-xl border border-border/60 bg-card p-3">
      <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p>
      <p className="mt-1.5 text-lg font-bold leading-none tabular-nums">
        {typeof value === 'number' && format ? (
          <AnimatedNumber value={value} format={format} />
        ) : (
          value
        )}
      </p>
    </div>
  )
}
