import { db } from '../../src/lib/db'
const c18 = await db.customer.findUnique({ where: { id: 18 }, select: { id: true, name: true, phone: true } })
const c19 = await db.customer.findUnique({ where: { id: 19 }, select: { id: true, name: true, phone: true } })
console.log('LOCAL customer 18:', JSON.stringify(c18))
console.log('LOCAL customer 19:', JSON.stringify(c19))
console.log('LOCAL customers total:', await db.customer.count())
const tx = await db.inventoryTransaction.findMany({ where: { id: { gte: 467 } }, select: { id: true, productId: true, quantityChange: true, orderId: true } })
console.log('LOCAL inventory_tx 467+:', JSON.stringify(tx))
const p = await db.product.findMany({ where: { id: { in: [6, 9, 296] } }, select: { id: true, name: true, stock: true } })
console.log('LOCAL products 6/9/296:', JSON.stringify(p))
const inEv = await db.hybridEvent.findMany({ where: { direction: 'in', status: 'applied', id: { gt: 1320 } }, select: { entity: true, entityId: true, operation: true } })
console.log('recent applied in-events:', JSON.stringify(inEv))
const cursor = await db.hybridSyncState.findUnique({ where: { key: 'pull.cursor' } })
const rem = await db.hybridSyncState.findUnique({ where: { key: 'pull.remaining' } })
console.log('cursor:', cursor?.value, 'remaining:', rem?.value)
await db.$disconnect()
